[versions]
kilua-rpc = "0.0.41"
kilua-rpc-published = "0.0.41"
kotlin = "2.3.10-RC"
dokka = "2.2.0-Beta"
nmcp = "1.4.4"
ksp = "2.3.5"
gradle-plugin-publish = "2.0.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.7.1"
wrappers = "2026.1.17"
javalin = "6.7.0"
jooby = "4.0.15"
ktor = "3.4.0"
koin = "4.1.1"
koin-annotations = "2.3.1"
micronaut = "4.10.7"
micronaut-plugins = "4.6.1"
spring-boot = "4.0.2"
vertx = "5.0.7"
tomlj = "1.1.1"
jackson-module-kotlin2 = "2.21.0"
jackson-module-kotlin3 = "3.0.4"
logback = "1.5.27"
shadow = "9.3.1"
testng = "7.12.0"
hamcrest = "3.0"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
wrappers-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "wrappers" }
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jooby-kotlin = { module = "io.jooby:jooby-kotlin", version.ref = "jooby" }
jooby-netty = { module = "io.jooby:jooby-netty", version.ref = "jooby" }
jooby-jackson = { module = "io.jooby:jooby-jackson", version.ref = "jooby" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
micronaut-platform = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "spring-boot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
vertx-web = { module = "io.vertx:vertx-web", version.ref = "vertx" }
vertx-lang-kotlin = { module = "io.vertx:vertx-lang-kotlin", version.ref = "vertx" }
vertx-lang-kotlin-coroutines = { module = "io.vertx:vertx-lang-kotlin-coroutines", version.ref = "vertx" }
vertx-launcher-application = { module = "io.vertx:vertx-launcher-application", version.ref = "vertx" }
vertx-codegen-api = { module = "io.vertx:vertx-codegen-api", version.ref = "vertx" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
jackson-module-kotlin2 = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-module-kotlin2" }
jackson-module-kotlin3 = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson-module-kotlin3" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
shadow-gradle-plugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
testng = { module = "org.testng:testng", version.ref = "testng" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
kilua-rpc-javalin = { module = "dev.kilua:kilua-rpc-javalin", version.ref = "kilua-rpc-published" }
kilua-rpc-javalin-koin = { module = "dev.kilua:kilua-rpc-javalin-koin", version.ref = "kilua-rpc-published" }
kilua-rpc-jooby = { module = "dev.kilua:kilua-rpc-jooby", version.ref = "kilua-rpc-published" }
kilua-rpc-jooby-koin = { module = "dev.kilua:kilua-rpc-jooby-koin", version.ref = "kilua-rpc-published" }
kilua-rpc-ktor = { module = "dev.kilua:kilua-rpc-ktor", version.ref = "kilua-rpc-published" }
kilua-rpc-ktor-koin = { module = "dev.kilua:kilua-rpc-ktor-koin", version.ref = "kilua-rpc-published" }
kilua-rpc-spring-boot = { module = "dev.kilua:kilua-rpc-spring-boot", version.ref = "kilua-rpc-published" }
kilua-rpc-micronaut = { module = "dev.kilua:kilua-rpc-micronaut", version.ref = "kilua-rpc-published" }
kilua-rpc-vertx = { module = "dev.kilua:kilua-rpc-vertx", version.ref = "kilua-rpc-published" }
kilua-rpc-vertx-koin = { module = "dev.kilua:kilua-rpc-vertx-koin", version.ref = "kilua-rpc-published" }

[plugins]
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jooby = { id = "io.jooby.run", version.ref = "jooby" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-plugins" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronaut-plugins" }
kilua-rpc = { id = "dev.kilua.rpc", version.ref = "kilua-rpc-published" }
